# ./deploy.yml

- hosts: nginx
  remote_user: kjones
  sudo: yes
  vars_files:
    - 'vars.yml'
  tasks:
    - include: 'tasks/install_dependencies.yml'
    - include: 'tasks/install_nginx_plus.yml'
    - include: 'tasks/copy_configurations.yml'
